[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.198", features = ["derive"] }
sqlx = { version = "0.7.4", default-features = false, features = ["chrono"] }
chrono = { version = "0.4", features = ["serde"] }
